// This file was generated by `cargo dev update_lints`.
// Use that command to update this file and do not edit by hand.
// Manual edits will be overwritten.

store.register_group(true, "clippy::cargo", Some("clippy_cargo"), [
    Some(LintId::of(cargo_common_metadata::CARGO_COMMON_METADATA)),
    Some(LintId::of(feature_name::NEGATIVE_FEATURE_NAMES)),
    Some(LintId::of(feature_name::REDUNDANT_FEATURE_NAMES)),
    Some(LintId::of(multiple_crate_versions::MULTIPLE_CRATE_VERSIONS)),
    Some(LintId::of(wildcard_dependencies::WILDCARD_DEPENDENCIES)),
].iter().copied().flatten().collect::<Vec<_>>())
