[crates]
# Binaries projects
cargo = { name = 'cargo', version = '0.64.0', mode = 'bin', online_link = 'https://docs.rs/cargo/{version}/src/{file}.html#{line}' }
ripgrep = { name = 'ripgrep', version = '14.1.0', mode = 'bin' }
bat = { name = 'bat', version = '0.24.0', mode = 'bin' }
fend = { name = 'fend', version = '1.5.0', mode = 'bin' }
mdbook = { name = 'mdbook', version = '0.4.40', mode = 'bin' }

# Bigger crates from ICE issues:
wasmi = { name = 'wasmi', version = '0.35.0', mode = 'lib' }
wgpu = { name = 'wgpu', version = '0.20.1', mode = 'lib' }
bytes = { name = 'bytes', version = '1.6.1', mode = 'lib' }
skrifa = { name = 'skrifa', version = '0.19.3', mode = 'lib' }

# Random crates which are part of the default test set
puffin = { name = 'puffin', version = '0.19.0', mode = 'lib' }

# Top ~200 crates from crates.io
syn = { name = 'syn', version = '2.0.71' , mode = 'lib' }
bitflags = { name = 'bitflags', version = '2.6.0' , mode = 'lib' }
hashbrown = { name = 'hashbrown', version = '0.14.5' , mode = 'lib' }
base64 = { name = 'base64', version = '0.22.1' , mode = 'lib' }
regex-syntax = { name = 'regex-syntax', version = '0.8.4' , mode = 'lib' }
proc-macro2 = { name = 'proc-macro2', version = '1.0.86' , mode = 'lib' }
indexmap = { name = 'indexmap', version = '2.2.6' , mode = 'lib' }
quote = { name = 'quote', version = '1.0.36' , mode = 'lib' }
regex-automata = { name = 'regex-automata', version = '0.4.7' , mode = 'lib' }
libc = { name = 'libc', version = '0.2.155' , mode = 'lib' }
serde = { name = 'serde', version = '1.0.204' , mode = 'lib' }
itertools = { name = 'itertools', version = '0.13.0' , mode = 'lib' }
heck = { name = 'heck', version = '0.5.0' , mode = 'lib' }
memchr = { name = 'memchr', version = '2.7.4' , mode = 'lib' }
serde_derive = { name = 'serde_derive', version = '1.0.204' , mode = 'lib' }
unicode-ident = { name = 'unicode-ident', version = '1.0.12' , mode = 'lib' }
autocfg = { name = 'autocfg', version = '1.3.0' , mode = 'lib' }
cfg-if = { name = 'cfg-if', version = '1.0.0' , mode = 'lib' }
aho-corasick = { name = 'aho-corasick', version = '1.1.3' , mode = 'lib' }
getrandom = { name = 'getrandom', version = '0.2.15' , mode = 'lib' }
rand_core = { name = 'rand_core', version = '0.6.4' , mode = 'lib' }
serde_json = { name = 'serde_json', version = '1.0.120' , mode = 'lib' }
itoa = { name = 'itoa', version = '1.0.11' , mode = 'lib' }
rand = { name = 'rand', version = '0.8.5' , mode = 'lib' }
ryu = { name = 'ryu', version = '1.0.18' , mode = 'lib' }
once_cell = { name = 'once_cell', version = '1.19.0' , mode = 'lib' }
rustix = { name = 'rustix', version = '0.38.34' , mode = 'lib' }
regex = { name = 'regex', version = '1.10.5' , mode = 'lib' }
log = { name = 'log', version = '0.4.22' , mode = 'lib' }
parking_lot_core = { name = 'parking_lot_core', version = '0.9.10' , mode = 'lib' }
cc = { name = 'cc', version = '1.1.5' , mode = 'lib' }
strsim = { name = 'strsim', version = '0.11.1' , mode = 'lib' }
clap = { name = 'clap', version = '4.5.9' , mode = 'lib' }
parking_lot = { name = 'parking_lot', version = '0.12.3' , mode = 'lib' }
smallvec = { name = 'smallvec', version = '2.0.0-alpha.6' , mode = 'lib' }
thiserror-impl = { name = 'thiserror-impl', version = '1.0.63' , mode = 'lib' }
thiserror = { name = 'thiserror', version = '1.0.63' , mode = 'lib' }
linux-raw-sys = { name = 'linux-raw-sys', version = '0.6.4' , mode = 'lib' }
socket2 = { name = 'socket2', version = '0.5.7' , mode = 'lib' }
idna = { name = 'idna', version = '1.0.2' , mode = 'lib' }
fastrand = { name = 'fastrand', version = '2.1.0' , mode = 'lib' }
either = { name = 'either', version = '1.13.0' , mode = 'lib' }
num-traits = { name = 'num-traits', version = '0.2.19' , mode = 'lib' }
rand_chacha = { name = 'rand_chacha', version = '0.3.1' , mode = 'lib' }
lazy_static = { name = 'lazy_static', version = '1.5.0' , mode = 'lib' }
semver = { name = 'semver', version = '1.0.23' , mode = 'lib' }
lock_api = { name = 'lock_api', version = '0.4.12' , mode = 'lib' }
scopeguard = { name = 'scopeguard', version = '1.2.0' , mode = 'lib' }
ahash = { name = 'ahash', version = '0.8.11' , mode = 'lib' }
anyhow = { name = 'anyhow', version = '1.0.86' , mode = 'lib' }
rustls = { name = 'rustls', version = '0.23.11' , mode = 'lib' }
http = { name = 'http', version = '1.1.0' , mode = 'lib' }
toml_edit = { name = 'toml_edit', version = '0.22.16' , mode = 'lib' }
pin-project-lite = { name = 'pin-project-lite', version = '0.2.14' , mode = 'lib' }
spin = { name = 'spin', version = '0.9.8' , mode = 'lib' }
miniz_oxide = { name = 'miniz_oxide', version = '0.7.4' , mode = 'lib' }
memoffset = { name = 'memoffset', version = '0.9.1' , mode = 'lib' }
digest = { name = 'digest', version = '0.11.0-pre.8' , mode = 'lib' }
version_check = { name = 'version_check', version = '0.9.4' , mode = 'lib' }
clap_lex = { name = 'clap_lex', version = '0.7.1' , mode = 'lib' }
crossbeam-utils = { name = 'crossbeam-utils', version = '0.8.20' , mode = 'lib' }
toml = { name = 'toml', version = '0.8.15' , mode = 'lib' }
block-buffer = { name = 'block-buffer', version = '0.10.4' , mode = 'lib' }
time = { name = 'time', version = '0.3.36' , mode = 'lib' }
hyper = { name = 'hyper', version = '1.4.1' , mode = 'lib' }
url = { name = 'url', version = '2.5.2' , mode = 'lib' }
percent-encoding = { name = 'percent-encoding', version = '2.3.1' , mode = 'lib' }
tokio = { name = 'tokio', version = '1.38.1' , mode = 'lib' }
errno = { name = 'errno', version = '0.3.9' , mode = 'lib' }
uuid = { name = 'uuid', version = '1.10.0' , mode = 'lib' }
unicode-normalization = { name = 'unicode-normalization', version = '0.1.23' , mode = 'lib' }
ppv-lite86 = { name = 'ppv-lite86', version = '0.2.17' , mode = 'lib' }
futures-core = { name = 'futures-core', version = '0.3.30' , mode = 'lib' }
http-body = { name = 'http-body', version = '1.0.1' , mode = 'lib' }
tinyvec = { name = 'tinyvec', version = '1.8.0' , mode = 'lib' }
futures-util = { name = 'futures-util', version = '0.3.30' , mode = 'lib' }
futures-task = { name = 'futures-task', version = '0.3.30' , mode = 'lib' }
sha2 = { name = 'sha2', version = '0.11.0-pre.3' , mode = 'lib' }
ring = { name = 'ring', version = '0.17.8' , mode = 'lib' }
slab = { name = 'slab', version = '0.4.9' , mode = 'lib' }
chrono = { name = 'chrono', version = '0.4.38' , mode = 'lib' }
futures-sink = { name = 'futures-sink', version = '0.3.30' , mode = 'lib' }
futures-channel = { name = 'futures-channel', version = '0.3.30' , mode = 'lib' }
num_cpus = { name = 'num_cpus', version = '1.16.0' , mode = 'lib' }
untrusted = { name = 'untrusted', version = '0.9.0' , mode = 'lib' }
tinyvec_macros = { name = 'tinyvec_macros', version = '0.1.1' , mode = 'lib' }
mio = { name = 'mio', version = '1.0.0' , mode = 'lib' }
byteorder = { name = 'byteorder', version = '1.5.0' , mode = 'lib' }
form_urlencoded = { name = 'form_urlencoded', version = '1.2.1' , mode = 'lib' }
unicode-bidi = { name = 'unicode-bidi', version = '0.3.15' , mode = 'lib' }
futures-io = { name = 'futures-io', version = '0.3.30' , mode = 'lib' }
tokio-util = { name = 'tokio-util', version = '0.7.11' , mode = 'lib' }
rustls-pemfile = { name = 'rustls-pemfile', version = '2.1.2' , mode = 'lib' }
generic-array = { name = 'generic-array', version = '1.1.0' , mode = 'lib' }
tracing = { name = 'tracing', version = '0.1.40' , mode = 'lib' }
equivalent = { name = 'equivalent', version = '1.0.1' , mode = 'lib' }
tracing-core = { name = 'tracing-core', version = '0.1.32' , mode = 'lib' }
pin-utils = { name = 'pin-utils', version = '0.1.0' , mode = 'lib' }
tempfile = { name = 'tempfile', version = '3.10.1' , mode = 'lib' }
h2 = { name = 'h2', version = '0.4.5' , mode = 'lib' }
futures = { name = 'futures', version = '0.3.30' , mode = 'lib' }
typenum = { name = 'typenum', version = '1.17.0' , mode = 'lib' }
winnow = { name = 'winnow', version = '0.6.13' , mode = 'lib' }
cpufeatures = { name = 'cpufeatures', version = '0.2.12' , mode = 'lib' }
nix = { name = 'nix', version = '0.29.0' , mode = 'lib' }
fnv = { name = 'fnv', version = '1.0.7' , mode = 'lib' }
tokio-rustls = { name = 'tokio-rustls', version = '0.26.0' , mode = 'lib' }
iana-time-zone = { name = 'iana-time-zone', version = '0.1.60' , mode = 'lib' }
rustls-webpki = { name = 'rustls-webpki', version = '0.102.5' , mode = 'lib' }
crc32fast = { name = 'crc32fast', version = '1.4.2' , mode = 'lib' }
adler = { name = 'adler', version = '1.0.2' , mode = 'lib' }
pkg-config = { name = 'pkg-config', version = '0.3.30' , mode = 'lib' }
redox_syscall = { name = 'redox_syscall', version = '0.5.3' , mode = 'lib' }
nom = { name = 'nom', version = '8.0.0-alpha2' , mode = 'lib' }
rustc_version = { name = 'rustc_version', version = '0.4.0' , mode = 'lib' }
futures-macro = { name = 'futures-macro', version = '0.3.30' , mode = 'lib' }
clap_derive = { name = 'clap_derive', version = '4.5.8' , mode = 'lib' }
futures-executor = { name = 'futures-executor', version = '0.3.30' , mode = 'lib' }
event-listener = { name = 'event-listener', version = '5.3.1' , mode = 'lib' }
num-integer = { name = 'num-integer', version = '0.1.46' , mode = 'lib' }
time-macros = { name = 'time-macros', version = '0.2.18' , mode = 'lib' }
flate2 = { name = 'flate2', version = '1.0.30' , mode = 'lib' }
tokio-macros = { name = 'tokio-macros', version = '2.3.0' , mode = 'lib' }
strum_macros = { name = 'strum_macros', version = '0.26.4' , mode = 'lib' }
tracing-attributes = { name = 'tracing-attributes', version = '0.1.27' , mode = 'lib' }
async-trait = { name = 'async-trait', version = '0.1.81' , mode = 'lib' }
crypto-common = { name = 'crypto-common', version = '0.1.6' , mode = 'lib' }
unicode-width = { name = 'unicode-width', version = '0.1.13' , mode = 'lib' }
anstyle = { name = 'anstyle', version = '1.0.7' , mode = 'lib' }
object = { name = 'object', version = '0.36.1' , mode = 'lib' }
gimli = { name = 'gimli', version = '0.31.0' , mode = 'lib' }
crossbeam-epoch = { name = 'crossbeam-epoch', version = '0.9.18' , mode = 'lib' }
thread_local = { name = 'thread_local', version = '1.1.8' , mode = 'lib' }
strum = { name = 'strum', version = '0.26.3' , mode = 'lib' }
darling_core = { name = 'darling_core', version = '0.20.10' , mode = 'lib' }
darling_macro = { name = 'darling_macro', version = '0.20.10' , mode = 'lib' }
minimal-lexical = { name = 'minimal-lexical', version = '0.2.1' , mode = 'lib' }
clap_builder = { name = 'clap_builder', version = '4.5.9' , mode = 'lib' }
time-core = { name = 'time-core', version = '0.1.2' , mode = 'lib' }
httparse = { name = 'httparse', version = '1.9.4' , mode = 'lib' }
signal-hook-registry = { name = 'signal-hook-registry', version = '1.4.2' , mode = 'lib' }
hex = { name = 'hex', version = '0.4.3' , mode = 'lib' }
crossbeam-deque = { name = 'crossbeam-deque', version = '0.8.5' , mode = 'lib' }
zerocopy = { name = 'zerocopy', version = '0.7.35' , mode = 'lib' }
rustversion = { name = 'rustversion', version = '1.0.17' , mode = 'lib' }
env_logger = { name = 'env_logger', version = '0.11.3' , mode = 'lib' }
webpki-roots = { name = 'webpki-roots', version = '0.26.3' , mode = 'lib' }
rustc-demangle = { name = 'rustc-demangle', version = '0.1.24' , mode = 'lib' }
mime = { name = 'mime', version = '0.3.17' , mode = 'lib' }
termcolor = { name = 'termcolor', version = '1.4.1' , mode = 'lib' }
subtle = { name = 'subtle', version = '2.6.1' , mode = 'lib' }
walkdir = { name = 'walkdir', version = '2.5.0' , mode = 'lib' }
hermit-abi = { name = 'hermit-abi', version = '0.4.0' , mode = 'lib' }
pin-project = { name = 'pin-project', version = '1.1.5' , mode = 'lib' }
pin-project-internal = { name = 'pin-project-internal', version = '1.1.5' , mode = 'lib' }
try-lock = { name = 'try-lock', version = '0.2.5' , mode = 'lib' }
tracing-log = { name = 'tracing-log', version = '0.2.0' , mode = 'lib' }
httpdate = { name = 'httpdate', version = '1.0.3' , mode = 'lib' }
anstream = { name = 'anstream', version = '0.6.14' , mode = 'lib' }
crossbeam-channel = { name = 'crossbeam-channel', version = '0.5.13' , mode = 'lib' }
reqwest = { name = 'reqwest', version = '0.12.5' , mode = 'lib' }
want = { name = 'want', version = '0.3.1' , mode = 'lib' }
paste = { name = 'paste', version = '1.0.15' , mode = 'lib' }
anstyle-parse = { name = 'anstyle-parse', version = '0.2.4' , mode = 'lib' }
toml_datetime = { name = 'toml_datetime', version = '0.6.6' , mode = 'lib' }
anstyle-query = { name = 'anstyle-query', version = '1.1.0' , mode = 'lib' }
addr2line = { name = 'addr2line', version = '0.24.0' , mode = 'lib' }
glob = { name = 'glob', version = '0.3.1' , mode = 'lib' }
num-bigint = { name = 'num-bigint', version = '0.4.6' , mode = 'lib' }
backtrace = { name = 'backtrace', version = '0.3.73' , mode = 'lib' }
wasi = { name = 'wasi', version = '0.13.1+wasi-0.2.0' , mode = 'lib' }
tower-service = { name = 'tower-service', version = '0.3.2' , mode = 'lib' }
sync_wrapper = { name = 'sync_wrapper', version = '1.0.1' , mode = 'lib' }
libloading = { name = 'libloading', version = '0.8.4' , mode = 'lib' }
rayon = { name = 'rayon', version = '1.10.0' , mode = 'lib' }
colorchoice = { name = 'colorchoice', version = '1.0.1' , mode = 'lib' }
encoding_rs = { name = 'encoding_rs', version = '0.8.34' , mode = 'lib' }
deranged = { name = 'deranged', version = '0.3.11' , mode = 'lib' }
zeroize = { name = 'zeroize', version = '1.8.1' , mode = 'lib' }
utf8parse = { name = 'utf8parse', version = '0.2.2' , mode = 'lib' }
tracing-subscriber = { name = 'tracing-subscriber', version = '0.3.18' , mode = 'lib' }
hyper-rustls = { name = 'hyper-rustls', version = '0.27.2' , mode = 'lib' }
hmac = { name = 'hmac', version = '0.13.0-pre.3' , mode = 'lib' }
rayon-core = { name = 'rayon-core', version = '1.12.1' , mode = 'lib' }
same-file = { name = 'same-file', version = '1.0.6' , mode = 'lib' }
prost = { name = 'prost', version = '0.13.1' , mode = 'lib' }
sharded-slab = { name = 'sharded-slab', version = '0.1.7' , mode = 'lib' }
textwrap = { name = 'textwrap', version = '0.16.1' , mode = 'lib' }
bumpalo = {name = 'bumpalo', version = '3.16.0' , mode = 'lib' }
arrayvec = { name = 'arrayvec', version = '0.7.4' , mode = 'lib' }
