# If you want to check a local project it's usually easier to use:
# ```
# cargo dev lint <path>
# ```
#
# For testing you can also add sources to git and local repos like this:
# ```
# crate = {name = "crate", git_url = "https://github.com/name/repo.git", git_hash = "coo1cafe"}
# crate = {name = "crate", path = "/path/to/project"}
# ```

[crates]

# Some binaries
cargo = {name = "cargo", version = '0.80.0', mode = "bin", online_link = 'https://docs.rs/cargo/{version}/src/{file}.html#{line}' }
ripgrep = {name = "ripgrep", version = '14.1.0', mode = "bin" }
mdbook = {name = "mdbook", version = '0.4.40', mode = "lib" }

# Common libraries
rayon = {name = "rayon", version = '1.10.0', mode = "lib"}
serde = {name = "serde", version = '1.0.204', mode = "lib"}
bitflags = {name = "bitflags", version = '2.6.0', mode = "lib"}
log = {name = "log", version = '0.4.22', mode = "lib"}
quote = {name = "quote", version = '1.0.36', mode = "lib"}
proc-macro2 = {name =  "proc-macro2", version = '1.0.86', mode = "lib"}
rand = {name = "rand", version = '0.8.5', mode = "lib"}
rand_core = {name = "rand_core", version = '0.6.4', mode = "lib"}
regex = {name = "regex", version = '1.10.5', mode = "lib"}
syn = {name = "syn", version = '2.0.71', mode = "lib"}
anyhow = {name = "anyhow", version = '1.0.86', mode = "lib"}
async-trait = {name =  'async-trait', version = '0.1.81' , mode = "lib"}
cxx = {name = "cxx", version = '1.0.124', mode = "lib"}
ryu = {name = "ryu", version = '1.0.18', mode = "lib"}
thiserror = {name = "thiserror", version = '1.0.63', mode = "lib"}
serde_yaml = {name = "serde_yaml", version = '0.9.33', mode = "lib"}
puffin = {name = "puffin", version = '0.19.0', mode = "lib"}
bumpalo = {name = "bumpalo", version = '3.16.0', mode = "lib"}
wasmi = {name = "wasmi", version = '0.35.0', mode = "lib"}
base64 = {name = 'base64', version = '0.22.1', mode = "lib"}
once_cell = {name = 'once_cell', version = '1.19.0', mode = "lib"}
tokio = {name = 'tokio', version = '1.38.1', mode = "lib"}

[recursive]
ignore = [
    # Takes ~30s to lint
    "combine",
    # Has 1.2 million `clippy::match_same_arms`s
    "unicode-normalization",
]
